// Code generated by "stringer -type TokenType ./src"; DO NOT EDIT.

package pointsalad

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IDENTIFIER-0]
	_ = x[EQUAL-1]
	_ = x[NUMBER-2]
	_ = x[COLON-3]
	_ = x[COMMA-4]
	_ = x[SLASH-5]
	_ = x[PLUS-6]
	_ = x[MINUS-7]
	_ = x[GREATER-8]
}

const _TokenType_name = "IDENTIFIEREQUALNUMBERCOLONCOMMASLASHPLUSMINUSGREATER"

var _TokenType_index = [...]uint8{0, 10, 15, 21, 26, 31, 36, 40, 45, 52}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
