// Code generated by "stringer -type ActorActionType .\src\pointsalad"; DO NOT EDIT.

package pointsalad

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[PICK_VEG_FROM_MARKET-1]
	_ = x[PICK_POINT_FROM_MARKET-2]
	_ = x[PICK_TO_SWAP-3]
}

const _ActorActionType_name = "INVALIDPICK_VEG_FROM_MARKETPICK_POINT_FROM_MARKETPICK_TO_SWAP"

var _ActorActionType_index = [...]uint8{0, 7, 27, 49, 61}

func (i ActorActionType) String() string {
	if i < 0 || i >= ActorActionType(len(_ActorActionType_index)-1) {
		return "ActorActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActorActionType_name[_ActorActionType_index[i]:_ActorActionType_index[i+1]]
}
