// Code generated by "stringer -type ActorActionType .\game\pointsalad\"; DO NOT EDIT.

package pointsalad

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[pickVegFromMarket-1]
	_ = x[pickPointFromMarket-2]
	_ = x[pickToSwap-3]
	_ = x[Quit-4]
}

const _ActorActionType_name = "InvalidpickVegFromMarketpickPointFromMarketpickToSwapQuit"

var _ActorActionType_index = [...]uint8{0, 7, 24, 43, 53, 57}

func (i ActorActionType) String() string {
	if i < 0 || i >= ActorActionType(len(_ActorActionType_index)-1) {
		return "ActorActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActorActionType_name[_ActorActionType_index[i]:_ActorActionType_index[i+1]]
}
