// Code generated by "stringer -type CardType ./src"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PEPPER-0]
	_ = x[LETTUCE-1]
	_ = x[CARROT-2]
	_ = x[CABBAGE-3]
	_ = x[ONION-4]
	_ = x[TOMATO-5]
}

const _CardType_name = "PEPPERLETTUCECARROTCABBAGEONIONTOMATO"

var _CardType_index = [...]uint8{0, 6, 13, 19, 26, 31, 37}

func (i CardType) String() string {
	if i < 0 || i >= CardType(len(_CardType_index)-1) {
		return "CardType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardType_name[_CardType_index[i]:_CardType_index[i+1]]
}
