// Code generated by "stringer -type CardType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CARD_PEPPER-0]
	_ = x[CARD_LETTUCE-1]
	_ = x[CARD_CARROT-2]
	_ = x[CARD_CABBAGE-3]
	_ = x[CARD_ONION-4]
	_ = x[CARD_TOMATO-5]
}

const _CardType_name = "CARD_PEPPERCARD_LETTUCECARD_CARROTCARD_CABBAGECARD_ONIONCARD_TOMATO"

var _CardType_index = [...]uint8{0, 11, 23, 34, 46, 56, 67}

func (i CardType) String() string {
	if i < 0 || i >= CardType(len(_CardType_index)-1) {
		return "CardType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CardType_name[_CardType_index[i]:_CardType_index[i+1]]
}
